flowchart TD
cloned_files_TrickIT_frontend_src_components_Profile.js_Profile["<b>Profile</b><br/><small>(—)</small><br/><small>cloned_files\TrickIT\frontend\src\components\Profile.js</small><br/><small>[arrow_function]</small>"]
cloned_files_TrickIT_frontend_src_components_Dashboard.js_loadProfile["<b>loadProfile</b><br/><small>(—)</small><br/><small>cloned_files\TrickIT\frontend\src\components\Dashboard.js</small><br/><small>[arrow_function]</small>"]
cloned_files_TrickIT_frontend_src_components_Profile.js_Profile --> cloned_files_TrickIT_frontend_src_components_Dashboard.js_loadProfile