apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5173
        env:
        - name: VITE_BACKEND_URL
          value: "http://192.168.59.100:30008"